-- DO NOT MODIFY, THIS FILE IS GENERATED --
-- VERSION 0.1.0 --
---@meta

---@class ProtoLogic
---@field const_get_fueldensity fun(): number
---@field const_get_spaceshipthrust fun(): number
---@field const_get_spaceshipfuelconsumption fun(): number
---@field const_get_missilethrust fun(): number
---@field const_get_missilefuelconsumption fun(): number
---@field const_get_turretminelevation fun(): number
---@field const_get_turretmaxelevation fun(): number
---@field const_get_turretelevationspeed fun(): number
---@field const_get_turretbearingspeed fun(): number
---@field const_get_turretminfuse fun(): number
---@field const_get_turretmaxfuse fun(): number
---@field const_get_turretshellspeed fun(): number
---@field const_get_turretrefiretime fun(): number
---@field const_get_missileradarminrange fun(): number
---@field const_get_missileradarmaxrange fun(): number
---@field const_get_missileradarminangle fun(): number
---@field const_get_missileradarmaxangle fun(): number
---@field const_get_shipradarminangle fun(): number
---@field const_get_shipradarmaxangle fun(): number
---@field const_get_missilerefiretime fun(): number
---@field const_get_shipbasemass fun(): number
---@field const_get_missilebasemass fun(): number
---@field const_get_missilewheeltorque fun(): number
---@field const_get_shipwheeltorque fun(): number
---@field const_get_shipradius fun(): number
---@field const_get_missileradius fun(): number
---@field const_get_shipmaxcpufuel fun(): integer
---@field const_get_shipmincpufuel fun(): integer
---@field const_get_shippertickcpufuel fun(): integer
protologic = nil
