-- DO NOT MODIFY, THIS FILE IS GENERATED --
-- VERSION 0.2.0 --
---@meta
-- Contact info.

---@class protologic.RadarContactInfo
---@field id integer
---@field type integer
---@field signal_strength number
---@field x number
---@field y number
---@field z number
